# Script mode: cmake -DOUTPUT=<file.cpp> -DFILES=<a;b;c> -P AvenEmbedGenerate.cmake

set(body "// Generated by AvenEmbedGenerate.cmake. Do not edit.\n#include <cstddef>\n#include <cstring>\n\nnamespace aven::embedded {\n\n")
set(table "")
set(index 0)
foreach(file ${FILES})
    get_filename_component(name ${file} NAME)
    file(READ ${file} hex HEX)
    string(LENGTH "${hex}" hexlen)
    math(EXPR size "${hexlen} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," hex "${hex}")
    string(APPEND body "static const unsigned char data${index}[] = {${hex}0x00};\n")
    string(APPEND table "    {\"${name}\", data${index}, ${size}},\n")
    math(EXPR index "${index} + 1")
endforeach()

string(APPEND body "\nstruct Entry { const char* name; const unsigned char* data; std::size_t size; };\n")
string(APPEND body "static const Entry entries[] = {\n${table}    {nullptr, nullptr, 0}\n};\n\n")
string(APPEND body "const unsigned char* find(const char* name, std::size_t* size) {\n")
string(APPEND body "    for (const Entry* e = entries; e->name; ++e) {\n")
string(APPEND body "        if (std::strcmp(e->name, name) == 0) { if (size) *size = e->size; return e->data; }\n")
string(APPEND body "    }\n    if (size) *size = 0;\n    return nullptr;\n}\n\n} // namespace aven::embedded\n")

file(WRITE ${OUTPUT} "${body}")
